#!/bin/bash
set -e
. data/extra.sh

if [ ! -f grml-plus/grub/netbootme.lkrn ]; then
	echo "Adding netboot.me"
	wget -P .. -nc http://static.netboot.me/gpxe/netbootme.iso
	mkdir -p ../netbootme
	mount ../netbootme.iso ../netbootme -o ro,loop
	cp ../netbootme/gpxe.krn grml-plus/grub/netbootme.lkrn
	umount ../netbootme
fi

if [ ! -f grml-plus/grub/bfo.lkrn ]; then
	echo "Adding boot.fedoraproject.org"
	wget -P grml-plus/grub -nc \
		http://dl.fedoraproject.org/pub/alt/bfo/bfo.lkrn
fi
cat $DATADIR/netbootme.cfg >>grml-plus/grub/extras.cfg

extra_cleanup
