#!/bin/bash
set -e
. data/extra.sh

if [ ! -f grml-plus/chntpw.iso ]; then
	echo "Adding chntpw."
	wget -P .. -nc http://pogostick.net/~pnh/ntpasswd/cd110511.zip
	unzip ../cd110511.zip -d ../chntpw
	cp ../chntpw/cd110511.iso grml-plus/chntpw.iso
fi

cat $DATADIR/chntpw.cfg >>grml-plus/grub/extras.cfg
cp $DATADIR/run-chntpw.sh grml-plus/run-chntpw.sh

extra_cleanup
