#!/bin/bash
set -e
. data/extra.sh

mkdir -p efi/boot

if [ ! -f efi/boot/bootx64.efi -a ! -f efi/boot/protector.efi ]; then
	echo "Error: Please run ./add-uefi-support first!" >&2
	extra_cleanup
	exit 1
fi

if [ ! -f efi/boot/protector.efi ]; then
	mv efi/boot/bootx64.efi efi/boot/protector.efi
fi

perl $DATADIR/patch-grub-secure-boot.pl efi/boot/grub.efi

if [ "$1" == "shim" ]; then

if [ "`dpkg --print-architecture`" != "amd64" ]; then
	echo "Error: sbsigntools are only available for grml64!" >&2
	extra_cleanup
	exit 1
fi

if [ -f efi/boot/grml-plus-ca.crt -a ! -f efi/boot/grubx64.efi \
	-a ! -f ../certs/GrmlPlus.key ]; then
	# oops, we have a certificate, but no signed grub, and no signing key;
	# let's delete and re-generate the certificate
	rm efi/boot/grml-plus-ca.crt
fi

if [ ! -f efi/boot/grml-plus-ca.crt ]; then
	wget -P .. -nc https://raw.github.com/vathpela/pesign/master/src/certs/make-certs
	mkdir -p ../certs
	pushd ../certs
	bash ../make-certs GrmlPlus grml-plus \
		all codesign 1.3.6.1.4.1.311.10.3.1
	popd
	cp ../certs/ca.crt efi/boot/grml-plus-ca.crt
	openssl x509 -in efi/boot/grml-plus-ca.crt \
		-out efi/boot/grml-plus-ca.der -outform DER
fi

if [ ! -f efi/boot/grubx64.efi ]; then
	wget -P .. -nc http://download.opensuse.org/repositories/home:/jejb1:/UEFI/Debian_7.0/amd64/sbsigntools_0.6-2_amd64.deb
	dpkg -i ../sbsigntools_0.6-2_amd64.deb
	wget -P .. -nc 'http://github.com/schierlm/grml-plus-uefi-tools/releases/download/v0.2/skipsign.efi'
	sbsign --key ../certs/GrmlPlus.key --cert ../certs/GrmlPlus.crt \
		--output efi/boot/grubx64.efi ../skipsign.efi
fi

if [ ! -f efi/boot/MokManager.efi ]; then
	wget -P .. -nc http://www.codon.org.uk/~mjg59/shim-signed/shim-signed-0.2.tgz
	tar Cxfvz .. ../shim-signed-0.2.tgz
	cp ../shim-signed/MokManager.efi efi/boot
	cp ../shim-signed/shim.efi efi/boot/bootx64.efi
	rm -R ../shim-signed
fi

else
	if [ ! -f efi/boot/loader.efi ]; then
		wget -P .. -nc 'http://github.com/schierlm/grml-plus-uefi-tools/releases/download/v0.2/skipsign.efi'
		cp ../skipsign.efi efi/boot/loader.efi
	fi

	if [ ! -f efi/boot/hashtool.efi ]; then
		wget -P .. -nc http://blog.hansenpartnership.com/wp-uploads/2013/PreLoader.efi
		wget -P .. -nc http://blog.hansenpartnership.com/wp-uploads/2013/HashTool.efi
		cp ../HashTool.efi efi/boot/hashtool.efi
		cp ../PreLoader.efi efi/boot/bootx64.efi
	fi
fi

extra_cleanup
